@admin_token = Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0MTEiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3MTk0OTU5NjYsImV4cCI6MTcxOTQ5OTU2Nn0.76l1v6KcGN17TLFukrMwaJ1us7czN9l0oNafAUnvp-E
@participant_token = Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJxcXEiLCJyb2xlIjoiUEFSVElDSVBBTlQiLCJpYXQiOjE3MjAwMjIzMDQsImV4cCI6MTcyMDAyNTkwNH0.s1kK43Wk4DxUqCALCQXQCqbNIYagnOQJ2fexbz8ZFQE

### auth admin
POST http://localhost:8075/auth/123411/123

### auth participant
POST http://localhost:8075/auth/qqq/qqq

### POST Admin
POST http://localhost:8075/admin
Authorization: {{admin_token}}
content-type: application/json

{
  "username": "123",
  "password": "123",
  "firstName": "123",
  "lastName": "123",
  "position": "123"
}

### POST Admin
POST http://localhost:8075/admin
Authorization: {{participant_token}}
content-type: application/json

{
  "username": "123",
  "password": "123",
  "firstName": "123",
  "lastName": "123",
  "position": "123"
}

### GET Admin
GET http://localhost:8075/admin/2
Authorization: {{admin_token}}

### PUT Admin
PUT http://localhost:8075/admin
Authorization: {{admin_token}}
content-type: application/json

{
  "id": 4,
  "username": "123",
  "password": "123",
  "firstName": "123",
  "lastName": "123",
  "position": "zxc"
}

### DELETE Admin
DELETE http://localhost:8075/admin/4
Authorization: {{admin_token}}


### POST Participant
POST http://localhost:8075/participant
content-type: application/json

{
  "username": "qqq",
  "password": "qqq",
  "firstName": "John",
  "lastName": "Doe",
  "test": "qqq"
}

### GET Participant
GET http://localhost:8075/participant/1
Authorization: {{admin_token}}

### GET Participant by username
GET http://localhost:8075/participant/byName/qqq
Authorization: {{participant_token}}

### GET Participant
GET http://localhost:8075/participant/2
Authorization: {{participant_token}}

### PUT Participant
PUT http://localhost:8075/participant
Authorization: {{participant_token}}
content-type: application/json

{
  "id": 2,
  "username": "qqq",
  "password": "qqq",
  "firstName": "John",
  "lastName": "Doe"
}

### DELETE Participant
DELETE http://localhost:8075/participant/7
Authorization: {{admin_token}}

### DELETE Participant
DELETE http://localhost:8075/participant/3
Authorization: {{participant_token}}

### POST Quiz
POST http://localhost:8075/quiz/2?settings=amount=10

### GET Quiz
GET http://localhost:8075/quiz/1

### Get by participant
GET http://localhost:8075/quiz/byParticipant/2

### Delete
DELETE http://localhost:8075/quiz/3

